---
sudo: false
language: ruby
cache: bundler
rvm:
  - jruby-1.7.25
env:
  - KAFKA_VERSION=0.10.2.2 LOGSTASH_BRANCH=5.6
install: true
script: ci/build.sh
jdk: oraclejdk8
before_install: gem install bundler -v '< 2'
